### ISSUE TITLE
'then' errors when onFulfilled handlers is a non-function

### ISSUE THREAD

**Issue by Markus-Ende** [knee-cola/jest-mock-promise#10]
Hi there,

thanks for this nice promise mock object! I currently use it together with marbles testing in rxjs.

This works like a charm, but I found a little defect:
According to spec, the `then` method should replace any non-function `onFulfilled`-handlers with an identity function (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then).

So, this should print 'Hello World' to the console:
```ts
promise.then(null).then(console.log);
promise.resolve('Hello World');
```

PR incoming...

Regards
Markus

**Comment by knee-cola** [comment]
You pull request was merged. Thank you for your contribution!

**Comment by Markus-Ende** [comment]
Thanks for merging! Could you please also publish a new version of your package?

**Comment by knee-cola** [comment]
Done! The new version if available on NPM!
