### ISSUE TITLE
then() returns this

### ISSUE THREAD

**Issue by fabb** [knee-cola/jest-mock-promise#15]
The `then` function returns `this` which makes this mock promise not work correctly with client code in all cases. Client code that process the returned promise value with `then` transformations will receive the unmodified original result value on further `then` calls.

To fix this, a new Promise would need to be returned with the `onFulfilled` function applied.

https://github.com/knee-cola/jest-mock-promise/blob/master/lib/jest-mock-promise.ts#L221

**Comment by knee-cola** [comment]
I've implemented a fix for this issue + an unit test.

So this has been resolved in v1.1.12

Thank you for this report!
