### ISSUE TITLE
Missing support for `Promise.prototype.finally(onFinally)` method.

### ISSUE THREAD

**Issue by nikita240** [knee-cola/jest-mock-promise#4]
`JestMockPromise` supports the `then()` and `catch()` methods, but seems to be missing support for the `finally()` method. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

**Comment by knee-cola** [comment]
This has been resolved in the v1.1.0

Thanks for your feedback!
